### ISSUE TITLE
How can i load RDF dump into my server's (remote) triple store?

### ISSUE THREAD

**Issue by ahmadchan** [JervenBolleman/sesame-loader#9]
I have around 6 GB RDF (single filed N3 triples) data which i want to store on remote triple store. I download sesame-loader project and ran that according to instructions. But its not storing any data on my local triple store. 
I tried as:
./load.sh -infile /home/ahmad/MyDevelopment/yusai/generatedoutputs/getImagefromTextout.rdf -dataFile /home/ahmad/ -commitInterval 4 -pushThreads 10 -baseUri http://cbakerlab.unbsj.ca:8080/liapi/
and i got the attached message as shown in figure attached. I will be thankful, if you help me to storing my data.

![sesame](https://f.cloud.github.com/assets/1532039/1460301/eda24b8e-4426-11e3-99d8-48af540fcede.png)

**Comment by JervenBolleman** [comment]
@ahmadchan sorry for never responding, the tool was really meant for local use only. It is obsolete and there are many better solutions out there.
